CREATE TABLE STUDENT (
  ID INT PRIMARY KEY,
  NAME TEXT,
  GRADE TEXT,
  AGE INT );
  
  DROP TABLE STUDENT;
  
  INSERT INTO STUDENT (ID , NAME , GRADE , AGE ) VALUES (1 , 'BEN' , 'A' , 20);
  
  SELECT * FROM STUDENT;
  
  ALTER TABLE STUDENT 
  ADD COLUMN CLUB TEXT;
  INSERT INTO STUDENT (ID , NAME , GRADE , AGE  ) VALUES (1 , 'BEN' , 'A' , 20);
  
  UPDATE STUDENT
  SET CLUB = 'SOSC'
  WHERE NAME = 'BEN';
  drop table student